FROM xhofe/alist:latest AS alist

FROM node:gallium-alpine
USER 10001
WORKDIR /root/
COPY --from=alist   /opt/alist/alist /usr/bin
RUN apk add --no-cache bash && chmod +x /usr/bin/alist
RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime 
EXPOSE 5244
EXPOSE 5344
CMD [ "alist","server","--no-prefix"]
