FROM node:gallium-alpine
ARG TARGETARCH
ARG TARGETVARIANT
WORKDIR /root/


COPY entrypoint-alist.sh /entrypoint.sh
RUN apk add --no-cache bash && chmod +x /entrypoint.sh

CMD [ "chmod +x alist-$TARGETARCH$TARGETVARIANT" ]
ADD alist-$TARGETARCH$TARGETVARIANT /usr/bin/alist
RUN chmod +x /usr/bin/alist
RUN apk --no-cache add ca-certificates tini
RUN apk add tzdata && \
	cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
	echo "Asia/Shanghai" > /etc/timezone && \
	apk del tzdata
RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime 
EXPOSE 5244
CMD [ "/entrypoint.sh" ]

USER 10001
