FROM node:gallium-alpine
USER 10001
ARG TARGETARCH
ARG TARGETVARIANT
WORKDIR /root/
CMD [ "chmod +x alist-$TARGETARCH$TARGETVARIANT" ]
ADD alist-$TARGETARCH$TARGETVARIANT /usr/bin/alist
RUN chmod +x /usr/bin/alist
RUN apk add --no-cache bash && chmod +x /usr/bin/alist
RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime 
EXPOSE 5244
EXPOSE 5344
CMD [ "alist","server","--no-prefix"]
